name: ios_player
description: A SwiftUI-based iOS video player plugin for Flutter.
version: 0.0.1

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IosPlayerPlugin
